name: adventofcode
description: solutions for advent of code
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0-0

dependencies:
  collection: ^1.17.0
  crypto: ^3.0.3
  meta: ^1.8.0
  more: ^4.0.0

dev_dependencies:
  test: ^1.22.0
